on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        path: main #to reference files from this repo, the filepath to use will be $GITHUB_WORKSPACE/main

    - name: Set current timestamp as output variable
      run: |
          echo "::set-output name=timestamp::$(date +'%Y-%m-%dT%H:%M')"
          echo "::set-output name=branch::${GITHUB_REF##*/}"
      id: set_vars #set snapshot related information (branch and timestamp)

    - name: Create snapshot directory required for Batfish
      run: |
        mkdir -p $GITHUB_WORKSPACE/tmp/configs
        mkdir -p $GITHUB_WORKSPACE/tmp/batfish
        cp $GITHUB_WORKSPACE/main/demonet/prod/configs/*.cfg $GITHUB_WORKSPACE/tmp/configs/
        cp $GITHUB_WORKSPACE/main/demonet/prod/batfish/* $GITHUB_WORKSPACE/tmp/batfish/
        echo "::set-output name=snapshot_dir::$GITHUB_WORKSPACE/tmp/"
      id: prepare_snapshot

    - name: Create snapshot artifact
      uses: actions/upload-artifact@v2
      with:
        name: batfish_snapshot
        path: ${{ steps.prepare_snapshot.outputs.snapshot_dir }}

    - name: Upload new snapshot to Batfish Enterprise server
      uses: saparikh/bfe-upload@v1.0
      with:
        server_name: ${{ secrets.BFE_SERVER_NAME }}
        server_ip: ${{ secrets.BFE_SERVER_IP }}
        snapshot_folder: ${{ steps.prepare_snapshot.outputs.snapshot_dir }}
        network_name: demonet
        snapshot_name: ${{ steps.set_vars.outputs.branch }}-${{ steps.set_vars.outputs.timestamp }}
        ssl_certificate: ${{ secrets.BFE_SSL_CERTIFICATE }}
        access_token: ${{ secrets.BFE_ACCESS_TOKEN }}
      id: upload_snapshot

    - name: Retrieve outputs from BFE upload action
      run: |
        echo ${{ steps.upload_snapshot.outputs.status }}
        echo ${{ steps.upload_snapshot.outputs.url }}
